from __future__ import annotations

"""
Train a churn prediction model in a reproducible, interview-friendly way.

Why this script exists:
- Converts notebook exploration into an end-to-end ML pipeline.
- Produces versioned artifacts and an explainable report.
- Makes the project presentable for senior/lead-level discussions.
"""

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
import zipfile

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler


DATASET_FILE_NAME = "WA_Fn-UseC_-Telco-Customer-Churn.csv"
DEFAULT_ARCHIVE_NAME = "archive.zip"

# Cost assumptions used for threshold tuning.
# You can discuss these assumptions in interviews and replace with real business costs.
DEFAULT_FALSE_NEGATIVE_COST = 5.0
DEFAULT_FALSE_POSITIVE_COST = 1.0

# Subgroups for basic fairness/sanity checks.
FAIRNESS_COLUMNS = ["gender", "SeniorCitizen"]


@dataclass
class TrainArtifacts:
    """Container for paths to artifacts generated by the training run."""

    model_path: Path
    metadata_path: Path
    metrics_path: Path
    report_path: Path
    validation_predictions_path: Path



def resolve_dataset_path(project_root: Path) -> Path:
    """
    Resolve dataset location.

    Search order:
    1) data/WA_Fn-UseC_-Telco-Customer-Churn.csv
    2) ./WA_Fn-UseC_-Telco-Customer-Churn.csv
    3) Extract from archive.zip into data/ and return that path
    """
    data_dir = project_root / "data"
    preferred_path = data_dir / DATASET_FILE_NAME

    if preferred_path.exists():
        return preferred_path

    root_path = project_root / DATASET_FILE_NAME
    if root_path.exists():
        return root_path

    archive_path = project_root / DEFAULT_ARCHIVE_NAME
    if archive_path.exists():
        data_dir.mkdir(exist_ok=True)
        with zipfile.ZipFile(archive_path, "r") as archive:
            names = archive.namelist()
            if DATASET_FILE_NAME not in names:
                raise FileNotFoundError(
                    f"{DATASET_FILE_NAME} not found inside {archive_path.name}."
                )
            archive.extract(DATASET_FILE_NAME, path=data_dir)
        extracted = data_dir / DATASET_FILE_NAME
        if extracted.exists():
            return extracted

    raise FileNotFoundError(
        "Dataset not found. Expected one of:\n"
        f"- {preferred_path}\n"
        f"- {root_path}\n"
        f"- {archive_path} containing {DATASET_FILE_NAME}"
    )



def load_and_clean_dataset(dataset_path: Path) -> pd.DataFrame:
    """
    Load and clean Telco churn data.

    Cleaning decisions mirror notebook logic and are intentionally explicit
    so they are easy to explain in a presentation.
    """
    df = pd.read_csv(dataset_path)

    # Convert `TotalCharges` to numeric, treating blank strings as missing.
    df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

    # Drop rows where `TotalCharges` is missing (small % of dataset).
    df = df.dropna(subset=["TotalCharges"]).copy()

    # Drop customer identifier to avoid leaking identity into model training.
    if "customerID" in df.columns:
        df = df.drop(columns=["customerID"])

    return df



def build_preprocessor(X: pd.DataFrame) -> tuple[ColumnTransformer, list[str], list[str]]:
    """Build column-wise preprocessing for numeric and categorical features."""
    numeric_features = X.select_dtypes(include=[np.number]).columns.tolist()
    categorical_features = [col for col in X.columns if col not in numeric_features]

    numeric_pipeline = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ]
    )

    categorical_pipeline = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore")),
        ]
    )

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_pipeline, numeric_features),
            ("cat", categorical_pipeline, categorical_features),
        ]
    )

    return preprocessor, numeric_features, categorical_features



def evaluate_model(model_pipeline: Pipeline, X_valid: pd.DataFrame, y_valid: pd.Series) -> dict[str, float]:
    """Evaluate model at default threshold 0.5 for baseline reporting."""
    proba = model_pipeline.predict_proba(X_valid)[:, 1]
    preds = (proba >= 0.5).astype(int)

    return {
        "roc_auc": float(roc_auc_score(y_valid, proba)),
        "precision": float(precision_score(y_valid, preds, zero_division=0)),
        "recall": float(recall_score(y_valid, preds, zero_division=0)),
        "f1": float(f1_score(y_valid, preds, zero_division=0)),
    }



def find_cost_optimized_threshold(
    y_true: pd.Series,
    probabilities: np.ndarray,
    false_negative_cost: float = DEFAULT_FALSE_NEGATIVE_COST,
    false_positive_cost: float = DEFAULT_FALSE_POSITIVE_COST,
) -> tuple[float, float]:
    """
    Find decision threshold that minimizes expected misclassification cost.

    Cost formula:
        total_cost = FN * false_negative_cost + FP * false_positive_cost
    """
    thresholds = np.linspace(0.05, 0.95, 91)
    best_threshold = 0.5
    best_cost = float("inf")

    for threshold in thresholds:
        preds = (probabilities >= threshold).astype(int)
        tn, fp, fn, tp = confusion_matrix(y_true, preds).ravel()
        cost = (fn * false_negative_cost) + (fp * false_positive_cost)

        if cost < best_cost:
            best_cost = float(cost)
            best_threshold = float(threshold)

    return best_threshold, best_cost



def subgroup_metrics(
    X_valid: pd.DataFrame,
    y_valid: pd.Series,
    probabilities: np.ndarray,
    threshold: float,
) -> dict[str, dict[str, dict[str, float]]]:
    """Compute basic subgroup performance metrics for fairness sanity checks."""
    result: dict[str, dict[str, dict[str, float]]] = {}
    predictions = (probabilities >= threshold).astype(int)

    for column in FAIRNESS_COLUMNS:
        if column not in X_valid.columns:
            continue

        column_metrics: dict[str, dict[str, float]] = {}
        for group_value, subset in X_valid.groupby(column):
            idx = subset.index
            y_subset = y_valid.loc[idx]
            pred_subset = predictions[y_valid.index.get_indexer(idx)]

            if len(y_subset) == 0:
                continue

            column_metrics[str(group_value)] = {
                "count": float(len(y_subset)),
                "positive_prediction_rate": float(np.mean(pred_subset)),
                "precision": float(precision_score(y_subset, pred_subset, zero_division=0)),
                "recall": float(recall_score(y_subset, pred_subset, zero_division=0)),
            }

        result[column] = column_metrics

    return result



def build_markdown_report(
    report_path: Path,
    model_name: str,
    cv_auc: float,
    baseline_metrics: dict[str, float],
    threshold: float,
    threshold_metrics: dict[str, float],
    best_cost: float,
    subgroup_results: dict[str, dict[str, dict[str, float]]],
) -> None:
    """Write a concise, presentation-ready training report in markdown."""
    lines: list[str] = [
        "# Churn Model Evaluation Report",
        "",
        f"Generated at: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Model Selection",
        "",
        f"- Selected model: **{model_name}**",
        f"- Cross-validation ROC-AUC (train folds): **{cv_auc:.4f}**",
        "",
        "## Validation Metrics (Default Threshold = 0.50)",
        "",
        f"- ROC-AUC: **{baseline_metrics['roc_auc']:.4f}**",
        f"- Precision: **{baseline_metrics['precision']:.4f}**",
        f"- Recall: **{baseline_metrics['recall']:.4f}**",
        f"- F1: **{baseline_metrics['f1']:.4f}**",
        "",
        "## Validation Metrics (Cost-Optimized Threshold)",
        "",
        f"- Threshold: **{threshold:.2f}**",
        f"- Expected misclassification cost: **{best_cost:.2f}**",
        f"- Precision: **{threshold_metrics['precision']:.4f}**",
        f"- Recall: **{threshold_metrics['recall']:.4f}**",
        f"- F1: **{threshold_metrics['f1']:.4f}**",
        "",
        "## Subgroup Sanity Check",
        "",
        "These checks are not a full fairness audit, but they help identify large group-level gaps early.",
        "",
    ]

    for column, groups in subgroup_results.items():
        lines.append(f"### {column}")
        lines.append("")
        if not groups:
            lines.append("- No subgroup values found in validation split.")
            lines.append("")
            continue

        for group_name, metrics in groups.items():
            lines.append(
                f"- **{group_name}** | count={metrics['count']:.0f}, "
                f"positive_rate={metrics['positive_prediction_rate']:.3f}, "
                f"precision={metrics['precision']:.3f}, recall={metrics['recall']:.3f}"
            )
        lines.append("")

    report_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")



def main() -> None:
    """Run full training pipeline and persist all artifacts."""
    project_root = Path(__file__).resolve().parents[1]

    models_dir = project_root / "models"
    presentation_dir = project_root / "presentation"
    models_dir.mkdir(exist_ok=True)
    presentation_dir.mkdir(exist_ok=True)

    dataset_path = resolve_dataset_path(project_root)
    df = load_and_clean_dataset(dataset_path)

    # Split features and target.
    y = df["Churn"].map({"Yes": 1, "No": 0}).astype(int)
    X = df.drop(columns=["Churn"])

    X_train, X_valid, y_train, y_valid = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y,
    )

    preprocessor, numeric_features, categorical_features = build_preprocessor(X_train)

    # Candidate models: linear baseline + non-linear tree model.
    candidate_models = {
        "logistic_regression": LogisticRegression(
            max_iter=2000,
            class_weight="balanced",
            solver="lbfgs",
        ),
        "random_forest": RandomForestClassifier(
            n_estimators=400,
            max_depth=None,
            min_samples_split=5,
            min_samples_leaf=2,
            class_weight="balanced_subsample",
            n_jobs=-1,
            random_state=42,
        ),
    }

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    candidate_summary: dict[str, dict[str, float]] = {}

    for model_name, estimator in candidate_models.items():
        pipeline = Pipeline(
            steps=[("preprocessor", preprocessor), ("model", estimator)]
        )

        cv_scores = cross_val_score(
            pipeline,
            X_train,
            y_train,
            scoring="roc_auc",
            cv=cv,
            n_jobs=-1,
        )

        pipeline.fit(X_train, y_train)
        valid_metrics = evaluate_model(pipeline, X_valid, y_valid)

        candidate_summary[model_name] = {
            "cv_roc_auc_mean": float(np.mean(cv_scores)),
            "cv_roc_auc_std": float(np.std(cv_scores)),
            "valid_roc_auc": valid_metrics["roc_auc"],
            "valid_precision": valid_metrics["precision"],
            "valid_recall": valid_metrics["recall"],
            "valid_f1": valid_metrics["f1"],
        }

    # Pick model with best validation ROC-AUC.
    best_model_name = max(
        candidate_summary,
        key=lambda name: candidate_summary[name]["valid_roc_auc"],
    )
    best_estimator = candidate_models[best_model_name]

    best_pipeline = Pipeline(
        steps=[("preprocessor", preprocessor), ("model", best_estimator)]
    )
    best_pipeline.fit(X_train, y_train)

    valid_probabilities = best_pipeline.predict_proba(X_valid)[:, 1]
    default_metrics = evaluate_model(best_pipeline, X_valid, y_valid)

    tuned_threshold, best_cost = find_cost_optimized_threshold(y_valid, valid_probabilities)
    tuned_predictions = (valid_probabilities >= tuned_threshold).astype(int)
    tuned_metrics = {
        "precision": float(precision_score(y_valid, tuned_predictions, zero_division=0)),
        "recall": float(recall_score(y_valid, tuned_predictions, zero_division=0)),
        "f1": float(f1_score(y_valid, tuned_predictions, zero_division=0)),
    }

    subgroup_results = subgroup_metrics(
        X_valid=X_valid,
        y_valid=y_valid,
        probabilities=valid_probabilities,
        threshold=tuned_threshold,
    )

    model_path = models_dir / "churn_model.joblib"
    metadata_path = models_dir / "model_metadata.json"
    metrics_path = models_dir / "training_metrics.json"
    report_path = presentation_dir / "model_evaluation_report.md"
    validation_predictions_path = models_dir / "validation_predictions.csv"

    joblib.dump(best_pipeline, model_path)

    metadata = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "dataset_path": str(dataset_path),
        "selected_model": best_model_name,
        "feature_columns": X.columns.tolist(),
        "numeric_features": numeric_features,
        "categorical_features": categorical_features,
        "threshold": tuned_threshold,
        "threshold_cost_assumptions": {
            "false_negative_cost": DEFAULT_FALSE_NEGATIVE_COST,
            "false_positive_cost": DEFAULT_FALSE_POSITIVE_COST,
        },
    }
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    metrics_payload = {
        "candidate_summary": candidate_summary,
        "selected_model": best_model_name,
        "default_threshold_metrics": default_metrics,
        "cost_optimized_threshold_metrics": {
            "threshold": tuned_threshold,
            "expected_cost": best_cost,
            **tuned_metrics,
        },
        "subgroup_metrics": subgroup_results,
    }
    metrics_path.write_text(json.dumps(metrics_payload, indent=2), encoding="utf-8")

    validation_df = X_valid.copy()
    validation_df["actual_churn"] = y_valid.values
    validation_df["predicted_probability"] = valid_probabilities
    validation_df["predicted_churn"] = tuned_predictions
    validation_df.to_csv(validation_predictions_path, index=False)

    build_markdown_report(
        report_path=report_path,
        model_name=best_model_name,
        cv_auc=candidate_summary[best_model_name]["cv_roc_auc_mean"],
        baseline_metrics=default_metrics,
        threshold=tuned_threshold,
        threshold_metrics=tuned_metrics,
        best_cost=best_cost,
        subgroup_results=subgroup_results,
    )

    artifacts = TrainArtifacts(
        model_path=model_path,
        metadata_path=metadata_path,
        metrics_path=metrics_path,
        report_path=report_path,
        validation_predictions_path=validation_predictions_path,
    )

    print("Training completed successfully.")
    print(f"Selected model: {best_model_name}")
    print(f"Cost-optimized threshold: {tuned_threshold:.2f}")
    print("Artifacts:")
    print(f"- Model: {artifacts.model_path}")
    print(f"- Metadata: {artifacts.metadata_path}")
    print(f"- Metrics: {artifacts.metrics_path}")
    print(f"- Validation predictions: {artifacts.validation_predictions_path}")
    print(f"- Report: {artifacts.report_path}")


if __name__ == "__main__":
    main()
